movement_rules = {
  "INSTANT": {
    "Level 1-1: Gem 1": "Bounce Pads",
    "Level 1-1: Gem 2": "Wall Jump + Grapple Hook || Bounce Pads",
    "Level 1-1: Gem 3": "Wall Jump + Grapple Hook + Carrots + Slam",
    "Level 1-1: Gem 4": "Wall Jump + Grapple Hook + Balloons",
    "Level 1-1: Gem 5": "Wall Jump + Grapple Hook + Balloons + Bounce Pads",
    "Level 1-1: Bonus Coin": "Wall Jump + Grapple Hook + Balloons",
    "Level 1-1: Complete": "Wall Jump + Grapple Hook + Balloons + Bounce Pads",
    "Level 1-2: Gem 1": "Wall Jump + Grapple Hook + Climb || Bounce Pads",
    "Level 1-2: Gem 2": "Wall Jump + Balloons || Grapple Hook + Climb",
    "Level 1-2: Gem 3": "Wall Jump + Grapple Hook + Climb || Bounce Pads + Cannons",
    "Level 1-2: Gem 4": "Wall Jump + Grapple Hook + Climb + Cannons",
    "Level 1-2: Gem 5": "Wall Jump + Grapple Hook + Climb + Cannons + Slam + Carrots",
    "Level 1-2: Complete": "Wall Jump + Grapple Hook + Climb + Cannons + Slam",
    "Level 1-3: Gem 1": "Bounce Pads + Grapple Hook",
    "Level 1-3: Gem 2": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim",
    "Level 1-3: Gem 3": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim",
    "Level 1-3: Gem 4": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Level 1-3: Gem 5": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Level 1-3: Bonus Coin": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Level 1-3: Complete": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Level 1-4: Gem 1": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons",
    "Level 1-4: Gem 2": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level 1-4: Gem 3": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level 1-4: Gem 4": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level 1-4: Gem 5": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level 1-4: Complete": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level 1-5: Gem 1": "Grapple Hook + Wall Jump + Slam",
    "Level 1-5: Gem 2": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Level 1-5: Gem 3": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Level 1-5: Gem 4": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb || Damage Boost",
    "Level 1-5: Gem 5": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb",
    "Level 1-5: Bonus Coin": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Level 1-5: Complete": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb",
    "Level 1-B: Gem 1": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Gem 2": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Gem 3": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Gem 4": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Gem 5": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Bonus Coin": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Beat REX": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level 1-B: Complete": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Bonus 1-1: Gem 1": "Wall Jump + Grapple Hook || Slam",
    "Bonus 1-1: Gem 2": "Wall Jump + Grapple Hook || Slam",
    "Bonus 1-1: Gem 3": "Wall Jump + Grapple Hook || Slam",
    "Bonus 1-2: Gem 1": "Grapple Hook",
    "Bonus 1-2: Gem 2": "Grapple Hook",
    "Bonus 1-2: Gem 3": "Grapple Hook",
    "Bonus 1-3: Gem 1": "Bounce Pads + Grapple Hook + Balloons",
    "Bonus 1-3: Gem 2": "Bounce Pads + Grapple Hook + Balloons",
    "Bonus 1-3: Gem 3": "Bounce Pads + Grapple Hook + Balloons",
    "Bonus 1-4: Gem 1": "Slam + Grapple Hook + Wall Jump",
    "Bonus 1-4: Gem 2": "Slam + Grapple Hook + Wall Jump",
    "Bonus 1-4: Gem 3": "Slam + Grapple Hook + Wall Jump",
    "Level 2-1: Gem 1": "Swim + Grapple Hook + Slam + Balloons",
    "Level 2-1: Gem 2": "Swim",
    "Level 2-1: Gem 3": "Swim + Wall Jump + Grapple Hook + Slam",
    "Level 2-1: Gem 4": "Swim + Wall Jump + Bounce Pads + Slam",
    "Level 2-1: Gem 5": "Swim + Wall Jump + Slam + Grapple Hook",
    "Level 2-1: Bonus Coin": "Swim + Wall Jump + Slam",
    "Level 2-1: Complete": "Swim + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Gem 1": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Gem 2": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Gem 3": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Gem 4": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Gem 5": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Bonus Coin": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-2: Complete": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level 2-3: Gem 1": "Grapple Hook + Wall Jump || Slam",
    "Level 2-3: Gem 2": "Grapple Hook + Wall Jump || Slam",
    "Level 2-3: Gem 3": "Grapple Hook + Wall Jump || Slam + Swim",
    "Level 2-3: Gem 4": "Grapple Hook + Wall Jump || Slam",
    "Level 2-3: Gem 5": "Grapple Hook + Wall Jump + Slam",
    "Level 2-3: Complete": "Grapple Hook + Wall Jump || Slam",
    "Level 2-4: Gem 1": "Wall Jump + Slam + Swim + Balloons || Damage Boost + Grapple Hook",
    "Level 2-4: Gem 2": "Wall Jump + Slam + Swim + Balloons + Grapple Hook",
    "Level 2-4: Gem 3": "Wall Jump + Slam + Swim + Wall Jump + Cannons + Grapple Hook",
    "Level 2-4: Gem 4": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Level 2-4: Gem 5": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Level 2-4: Bonus Coin": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Level 2-4: Complete": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Level 2-5: Gem 1": "Grapple Hook",
    "Level 2-5: Gem 2": "Grapple Hook",
    "Level 2-5: Gem 3": "Grapple Hook",
    "Level 2-5: Gem 4": "Grapple Hook + Wall Jump",
    "Level 2-5: Gem 5": "Grapple Hook + Wall Jump",
    "Level 2-5: Bonus Coin": "Grapple Hook",
    "Level 2-5: Complete": "Grapple Hook + Wall Jump",
    "Level 2-B: Gem 1": "Swim + Slam",
    "Level 2-B: Gem 2": "Swim + Slam + Bounce Pads + Wall Jump",
    "Level 2-B: Gem 3": "Swim + Slam + Bounce Pads + Wall Jump",
    "Level 2-B: Gem 4": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook",
    "Level 2-B: Gem 5": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook",
    "Level 2-B: Complete": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook + Balloons",
    "Level 2-B: Beat TANK": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook + Balloons",
    "Bonus 2-1: Gem 1": "Swim",
    "Bonus 2-1: Gem 2": "Swim",
    "Bonus 2-1: Gem 3": "Swim",
    "Bonus 2-2: Gem 1": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Bonus 2-2: Gem 2": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Bonus 2-2: Gem 3": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Bonus 2-3: Gem 1": "Wall Jump + Climb + Swim",
    "Bonus 2-3: Gem 2": "Wall Jump + Climb + Swim",
    "Bonus 2-3: Gem 3": "Wall Jump + Climb + Swim",
    "Bonus 2-4: Gem 1": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Bonus 2-4: Gem 2": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Bonus 2-4: Gem 3": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Level 3-1: Gem 1": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 3-1: Gem 2": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 3-1: Gem 3": "Wall Jump + Grapple Hook + Balloons || Damage Boost + Cannons",
    "Level 3-1: Gem 4": "Wall Jump + Grapple Hook + Cannons",
    "Level 3-1: Gem 5": "Wall Jump + Grapple Hook + Cannons",
    "Level 3-1: Bonus Coin": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 3-1: Complete": "Wall Jump + Grapple Hook + Cannons",
    "Level 3-2: Gem 1": "Bounce Pads + Grapple Hook",
    "Level 3-2: Gem 2": "Bounce Pads + Grapple Hook + Cannons + Balloons || Damage Boost",
    "Level 3-2: Gem 3": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Level 3-2: Gem 4": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Level 3-2: Gem 5": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Level 3-2: Complete": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Level 3-3: Gem 1": "Slam + Bounce Pads + Grapple Hook + Wall Jump",
    "Level 3-3: Gem 2": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons",
    "Level 3-3: Gem 3": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons",
    "Level 3-3: Gem 4": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Balloons + Swim",
    "Level 3-3: Gem 5": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons + Swim",
    "Level 3-3: Bonus Coin": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Balloons",
    "Level 3-3: Complete": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons + Swim",
    "Level 3-4: Gem 1": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Level 3-4: Gem 2": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Level 3-4: Gem 3": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Level 3-4: Gem 4": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Level 3-4: Gem 5": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Level 3-4: Bonus Coin": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Level 3-4: Complete": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Level 3-5: Gem 1": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Level 3-5: Gem 2": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Level 3-5: Gem 3": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Level 3-5: Gem 4": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Level 3-5: Gem 5": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Level 3-5: Bonus Coin": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Level 3-5: Complete": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Level 3-B: Gem 1": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Gem 2": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Gem 3": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Gem 4": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Gem 5": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Complete": "Cannons + Wall Jump + Grapple Hook",
    "Level 3-B: Beat FACE": "Cannons + Wall Jump + Grapple Hook",
    "Bonus 3-1: Gem 1": "Wall Jump + Grapple Hook",
    "Bonus 3-1: Gem 2": "Wall Jump + Grapple Hook",
    "Bonus 3-1: Gem 3": "Wall Jump + Grapple Hook",
    "Bonus 3-2: Gem 1": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Bonus 3-2: Gem 2": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Bonus 3-2: Gem 3": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Bonus 3-3: Gem 1": "Grapple Hook + Wall Jump + Climb",
    "Bonus 3-3: Gem 2": "Grapple Hook + Wall Jump + Climb",
    "Bonus 3-3: Gem 3": "Grapple Hook + Wall Jump + Climb",
    "Bonus 3-4: Gem 1": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Bonus 3-4: Gem 2": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Bonus 3-4: Gem 3": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Level 4-1: Gem 1": "Grapple Hook",
    "Level 4-1: Gem 2": "Grapple Hook + Balloons + Wall Jump",
    "Level 4-1: Gem 3": "Grapple Hook + Balloons + Wall Jump",
    "Level 4-1: Gem 4": "Grapple Hook + Balloons + Wall Jump",
    "Level 4-1: Gem 5": "Grapple Hook + Balloons + Wall Jump",
    "Level 4-1: Complete": "Grapple Hook + Balloons + Wall Jump",
    "Level 4-2: Gem 1": "Wall Jump + Grapple Hook + Balloons",
    "Level 4-2: Gem 2": "Wall Jump + Grapple Hook + Cannons + Slam",
    "Level 4-2: Gem 3": "Wall Jump + Grapple Hook + Cannons + Slam",
    "Level 4-2: Gem 4": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Level 4-2: Gem 5": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Level 4-2: Bonus Coin": "Wall Jump + Grapple Hook + Cannons",
    "Level 4-2: Complete": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Level 4-3: Gem 1": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level 4-3: Gem 2": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level 4-3: Gem 3": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level 4-3: Gem 4": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level 4-3: Gem 5": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim + Slam",
    "Level 4-3: Bonus Coin": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level 4-3: Complete": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim + Slam",
    "Level 4-4: Gem 1": "Wall Jump + Grapple Hook",
    "Level 4-4: Gem 2": "Wall Jump + Slam",
    "Level 4-4: Gem 3": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 4-4: Gem 4": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 4-4: Gem 5": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 4-4: Bonus Coin": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 4-4: Complete": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 4-5: Gem 1": "Grapple Hook + Cannons",
    "Level 4-5: Gem 2": "Grapple Hook + Cannons + Wall Jump",
    "Level 4-5: Gem 3": "Grapple Hook + Cannons + Wall Jump + Climb + Balloons",
    "Level 4-5: Gem 4": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Level 4-5: Gem 5": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Level 4-5: Bonus Coin": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Level 4-5: Complete": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Level 4-B: Gem 1": "Slam + Balloons + Grapple Hook",
    "Level 4-B: Gem 2": "Slam + Balloons + Grapple Hook + Wall Jump",
    "Level 4-B: Gem 3": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Level 4-B: Gem 4": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Level 4-B: Gem 5": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Level 4-B: Complete": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons + Cannons",
    "Level 4-B: Beat DRGN": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons + Cannons",
    "Bonus 4-1: Gem 1": "Grapple Hook + Wall Jump || Slam",
    "Bonus 4-1: Gem 2": "Grapple Hook + Wall Jump || Slam",
    "Bonus 4-1: Gem 3": "Grapple Hook + Wall Jump || Slam",
    "Bonus 4-2: Gem 1": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Bonus 4-2: Gem 2": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Bonus 4-2: Gem 3": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Bonus 4-3: Gem 1": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Bonus 4-3: Gem 2": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Bonus 4-3: Gem 3": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Bonus 4-4: Gem 1": "Cannons + Grapple Hook",
    "Bonus 4-4: Gem 2": "Cannons + Grapple Hook",
    "Bonus 4-4: Gem 3": "Cannons + Grapple Hook",
    "Level 5-1: Gem 1": "Cannons + Grapple Hook + Wall Jump",
    "Level 5-1: Gem 2": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Level 5-1: Gem 3": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Level 5-1: Gem 4": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Level 5-1: Gem 5": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Level 5-1: Bonus Coin": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Level 5-1: Complete": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Level 5-2: Gem 1": "Grapple Hook + Wall Jump + Swim + Slam + Balloons",
    "Level 5-2: Gem 2": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-2: Gem 3": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-2: Gem 4": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-2: Gem 5": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-2: Bonus Coin": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-2: Complete": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-3: Gem 1": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Gem 2": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Gem 3": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Gem 4": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Gem 5": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Bonus Coin": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level 5-3: Complete": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level 5-4: Gem 1": "Balloons + Grapple Hook",
    "Level 5-4: Gem 2": "Balloons + Grapple Hook",
    "Level 5-4: Gem 3": "Balloons + Grapple Hook + Cannons",
    "Level 5-4: Gem 4": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Level 5-4: Gem 5": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Level 5-4: Bonus Coin": "Balloons + Grapple Hook",
    "Level 5-4: Complete": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Level 5-5: Gem 1": "Wall Jump + Grapple Hook + Balloons",
    "Level 5-5: Gem 2": "Wall Jump + Grapple Hook",
    "Level 5-5: Gem 3": "Wall Jump + Grapple Hook + Balloons",
    "Level 5-5: Gem 4": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 5-5: Gem 5": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 5-5: Complete": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 5-5: Beat REX V2": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level 5-B: Gem 1": "Bounce Pads + Cannons + Wall Jump + Grapple Hook",
    "Level 5-B: Gem 2": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Carrots",
    "Level 5-B: Gem 3": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level 5-B: Gem 4": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level 5-B: Gem 5": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level 5-B: Complete": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level 5-B: Beat MECH": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level 5-B: Beat NUL": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Bonus 5-1: Gem 1": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Bonus 5-1: Gem 2": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Bonus 5-1: Gem 3": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Bonus 5-2: Gem 1": "Grapple Hook + Wall Jump",
    "Bonus 5-2: Gem 2": "Grapple Hook + Wall Jump",
    "Bonus 5-2: Gem 3": "Grapple Hook + Wall Jump",
    "Bonus 5-3: Gem 1": "Slam + Grapple Hook + Wall Jump",
    "Bonus 5-3: Gem 2": "Slam + Grapple Hook + Wall Jump",
    "Bonus 5-3: Gem 3": "Slam + Grapple Hook + Wall Jump",
    "Bonus 5-4: Gem 1": "Grapple Hook",
    "Bonus 5-4: Gem 2": "Grapple Hook",
    "Bonus 5-4: Gem 3": "Grapple Hook",
    "Level 6-1: Gem 1": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Level 6-1: Gem 2": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Level 6-1: Gem 3": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Level 6-1: Gem 4": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Level 6-1: Gem 5": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Level 6-2: Gem 1": "Grapple Hook + Bounce Pads + Cannons",
    "Level 6-2: Gem 2": "Grapple Hook + Bounce Pads + Cannons + Wall Jump",
    "Level 6-2: Gem 3": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Level 6-2: Gem 4": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Level 6-2: Gem 5": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Level 6-3: Gem 1": "Grapple Hook + Wall Jump",
    "Level 6-3: Gem 2": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons || Damage Boost",
    "Level 6-3: Gem 3": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Level 6-3: Gem 4": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Level 6-3: Gem 5": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Bonus 6-1: Gem 1": "Wall Jump + Balloons + Slam + Swim",
    "Bonus 6-1: Gem 2": "Wall Jump + Balloons + Slam + Swim",
    "Bonus 6-1: Gem 3": "Wall Jump + Balloons + Slam + Swim",
    "Bonus 6-2: Gem 1": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Bonus 6-2: Gem 2": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Bonus 6-2: Gem 3": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Bonus 6-3: Gem 1": "Grapple Hook",
    "Bonus 6-3: Gem 2": "Grapple Hook",
    "Bonus 6-3: Gem 3": "Grapple Hook",

    "Pet The Dog": "Grapple Hook + Bounce Pads + Balloons + Cannons + Wall Jump + Climb + Swim + Slam"
  }
}